package co.id.pegadaian.pasg2.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProvinsi generated by hbm2java
 */
@Entity
@Table(name = "TBL_PROVINSI", schema = "PASG2")
public class TblProvinsi  extends AuditTrail implements java.io.Serializable {

	private String kodeProvinsi;
	
	private String namaProvinsi;

	public TblProvinsi() {
	}

	public TblProvinsi(String kodeProvinsi, String namaProvinsi) {
		this.kodeProvinsi = kodeProvinsi;
		this.namaProvinsi = namaProvinsi;
	}

	

	@Id
	@Column(name = "KODE_PROVINSI", unique = true, nullable = false, length = 2)
	public String getKodeProvinsi() {
		return this.kodeProvinsi;
	}

	public void setKodeProvinsi(String kodeProvinsi) {
		this.kodeProvinsi = kodeProvinsi;
	}

	
	@Column(name = "NAMA_PROVINSI", nullable = false, length = 100)
	public String getNamaProvinsi() {
		return this.namaProvinsi;
	}

	public void setNamaProvinsi(String namaProvinsi) {
		this.namaProvinsi = namaProvinsi;
	}

}
