package co.id.pegadaian.pasg2.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBranch generated by hbm2java
 */
@Entity
@Table(name = "TBL_BRANCH", schema = "PASG2")
public class TblBranch extends AuditTrail implements java.io.Serializable {

	private String branchCode;
//	private String createBy;
//	private Date createDate;
//	private String updateBy;
//	private Date updateDate;
//	private BigDecimal versi;
	private String alternateId;
	private Date closeDate;
	private String kelas;
	private String isKonvensional;
	private String lvl;
	private String name;
	private String norekKasCabang;
	private Date openDate;
	private String parentId;
	private String parentAdministrasi;
	private String parentPemeriksaan;
	private String pinca;
	private String printer;
	private String produkDiterima;
	private String produkEksternalDiterima;
	private String skPinca;
	private String status;
	private String statusOperasional;
	private String telp;
	private Date tglSkPinca;
	private String versisbg;

	public TblBranch() {
	}

	public TblBranch(String branchCode, String lvl, String name) {
		this.branchCode = branchCode;
		this.lvl = lvl;
		this.name = name;
	}

	public TblBranch(String branchCode, 
			String alternateId, Date closeDate, String kelas,
			String isKonvensional, String lvl, String name,
			String norekKasCabang, Date openDate, String parentId,
			String parentAdministrasi, String parentPemeriksaan, String pinca,
			String printer, String produkDiterima,
			String produkEksternalDiterima, String skPinca, String status,
			String statusOperasional, String telp, Date tglSkPinca,
			String versisbg) {
		this.branchCode = branchCode;
//		this.createBy = createBy;
//		this.createDate = createDate;
//		this.updateBy = updateBy;
//		this.updateDate = updateDate;
//		this.versi = versi;
		this.alternateId = alternateId;
		this.closeDate = closeDate;
		this.kelas = kelas;
		this.isKonvensional = isKonvensional;
		this.lvl = lvl;
		this.name = name;
		this.norekKasCabang = norekKasCabang;
		this.openDate = openDate;
		this.parentId = parentId;
		this.parentAdministrasi = parentAdministrasi;
		this.parentPemeriksaan = parentPemeriksaan;
		this.pinca = pinca;
		this.printer = printer;
		this.produkDiterima = produkDiterima;
		this.produkEksternalDiterima = produkEksternalDiterima;
		this.skPinca = skPinca;
		this.status = status;
		this.statusOperasional = statusOperasional;
		this.telp = telp;
		this.tglSkPinca = tglSkPinca;
		this.versisbg = versisbg;
	}

	@Id
	@Column(name = "BRANCH_CODE", unique = true, nullable = false, length = 5)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	

	@Column(name = "ALTERNATE_ID", length = 6)
	public String getAlternateId() {
		return this.alternateId;
	}

	public void setAlternateId(String alternateId) {
		this.alternateId = alternateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CLOSE_DATE", length = 7)
	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	@Column(name = "KELAS", length = 1)
	public String getKelas() {
		return this.kelas;
	}

	public void setKelas(String kelas) {
		this.kelas = kelas;
	}

	@Column(name = "IS_KONVENSIONAL", length = 1)
	public String getIsKonvensional() {
		return this.isKonvensional;
	}

	public void setIsKonvensional(String isKonvensional) {
		this.isKonvensional = isKonvensional;
	}

	@Column(name = "LVL", nullable = false, length = 1)
	public String getLvl() {
		return this.lvl;
	}

	public void setLvl(String lvl) {
		this.lvl = lvl;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NOREK_KAS_CABANG", length = 15)
	public String getNorekKasCabang() {
		return this.norekKasCabang;
	}

	public void setNorekKasCabang(String norekKasCabang) {
		this.norekKasCabang = norekKasCabang;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OPEN_DATE", length = 7)
	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	@Column(name = "PARENT_ID", length = 5)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "PARENT_ADMINISTRASI", length = 5)
	public String getParentAdministrasi() {
		return this.parentAdministrasi;
	}

	public void setParentAdministrasi(String parentAdministrasi) {
		this.parentAdministrasi = parentAdministrasi;
	}

	@Column(name = "PARENT_PEMERIKSAAN", length = 5)
	public String getParentPemeriksaan() {
		return this.parentPemeriksaan;
	}

	public void setParentPemeriksaan(String parentPemeriksaan) {
		this.parentPemeriksaan = parentPemeriksaan;
	}

	@Column(name = "PINCA", length = 10)
	public String getPinca() {
		return this.pinca;
	}

	public void setPinca(String pinca) {
		this.pinca = pinca;
	}

	@Column(name = "PRINTER", length = 300)
	public String getPrinter() {
		return this.printer;
	}

	public void setPrinter(String printer) {
		this.printer = printer;
	}

	@Column(name = "PRODUK_DITERIMA", length = 100)
	public String getProdukDiterima() {
		return this.produkDiterima;
	}

	public void setProdukDiterima(String produkDiterima) {
		this.produkDiterima = produkDiterima;
	}

	@Column(name = "PRODUK_EKSTERNAL_DITERIMA", length = 100)
	public String getProdukEksternalDiterima() {
		return this.produkEksternalDiterima;
	}

	public void setProdukEksternalDiterima(String produkEksternalDiterima) {
		this.produkEksternalDiterima = produkEksternalDiterima;
	}

	@Column(name = "SK_PINCA", length = 60)
	public String getSkPinca() {
		return this.skPinca;
	}

	public void setSkPinca(String skPinca) {
		this.skPinca = skPinca;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "STATUS_OPERASIONAL", length = 1)
	public String getStatusOperasional() {
		return this.statusOperasional;
	}

	public void setStatusOperasional(String statusOperasional) {
		this.statusOperasional = statusOperasional;
	}

	@Column(name = "TELP", length = 15)
	public String getTelp() {
		return this.telp;
	}

	public void setTelp(String telp) {
		this.telp = telp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TGL_SK_PINCA", length = 7)
	public Date getTglSkPinca() {
		return this.tglSkPinca;
	}

	public void setTglSkPinca(Date tglSkPinca) {
		this.tglSkPinca = tglSkPinca;
	}

	@Column(name = "VERSISBG", length = 1)
	public String getVersisbg() {
		return this.versisbg;
	}

	public void setVersisbg(String versisbg) {
		this.versisbg = versisbg;
	}

}
