package co.id.pegadaian.pasg2.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblGroup generated by hbm2java
 */
@Entity
@Table(name = "TBL_GROUP", schema = "PASG2")
public class TblGroup extends AuditTrail implements java.io.Serializable {
	

	private BigDecimal groupId;
	private String groupName;
	private String jabatan;
	private String params;
	

	public TblGroup() {
	}

	public TblGroup(BigDecimal groupId, String groupName) {
		this.groupId = groupId;
		this.groupName = groupName;
	}


	@Id
	@Column(name = "GROUP_ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getGroupId() {
		return this.groupId;
	}

	public void setGroupId(BigDecimal groupId) {
		this.groupId = groupId;
	}



	@Column(name = "GROUP_NAME", nullable = false, length = 100)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "JABATAN", length = 5)
	public String getJabatan() {
		return this.jabatan;
	}

	public void setJabatan(String jabatan) {
		this.jabatan = jabatan;
	}

	@Column(name = "PARAMS", length = 500)
	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

}
