package co.id.pegadaian.pasg2.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblKelurahan generated by hbm2java
 */
@Entity
@Table(name = "TBL_KELURAHAN", schema = "PASG2")
public class TblKelurahan extends AuditTrail implements java.io.Serializable {

	private String kodePos;
	private String namaKelurahan;
	private String kodeKecamatan;
	private String idKelurahan;

	public TblKelurahan() {
	}

	@Column(name = "KODE_POS", length = 6)
	public String getKodePos() {
		return this.kodePos;
	}

	public void setKodePos(String kodePos) {
		this.kodePos = kodePos;
	}

	@Column(name = "NAMA_KELURAHAN", nullable = false, length = 100)
	public String getNamaKelurahan() {
		return this.namaKelurahan;
	}

	public void setNamaKelurahan(String namaKelurahan) {
		this.namaKelurahan = namaKelurahan;
	}

@Id
	@Column(name = "KODE_KECAMATAN", nullable = false, length = 6)
	public String getKodeKecamatan() {
		return this.kodeKecamatan;
	}

	public void setKodeKecamatan(String kodeKecamatan) {
		this.kodeKecamatan = kodeKecamatan;
	}
@Id
	@Column(name = "ID_KELURAHAN", nullable = false, length = 10)
	public String getIdKelurahan() {
		return this.idKelurahan;
	}

	public void setIdKelurahan(String idKelurahan) {
		this.idKelurahan = idKelurahan;
	}
	
	
}
