package co.id.pegadaian.pasg2.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblPriviledge generated by hbm2java
 */
@Entity
@Table(name = "TBL_PRIVILEDGE", schema = "PASG2")
public class TblPriviledge extends  AuditTrail implements java.io.Serializable {



	private char isAdd;
	private char isDelete;
	private char isUpdate;
	private char isView;
	private BigDecimal groupId;
	private BigDecimal menuId;

	
	public TblPriviledge(char isAdd, char isDelete, char isUpdate, char isView,
			BigDecimal groupId, BigDecimal menuId) {
		super();
		this.isAdd = isAdd;
		this.isDelete = isDelete;
		this.isUpdate = isUpdate;
		this.isView = isView;
		this.groupId = groupId;
		this.menuId = menuId;
	}

	
	
@Id
	@Column(name = "GROUP_ID", nullable = false, scale = 0)
	public BigDecimal getGroupId() {
		return this.groupId;
	}

	public void setGroupId(BigDecimal groupId) {
		this.groupId = groupId;
	}
	@Id
	@Column(name = "MENU_ID", nullable = false, scale = 0)
	public BigDecimal getMenuId() {
		return this.menuId;
	}

	public void setMenuId(BigDecimal menuId) {
		this.menuId = menuId;
	}

	

	public TblPriviledge() {
	}

	
	@Column(name = "IS_ADD", nullable = false, length = 1)
	public char getIsAdd() {
		return this.isAdd;
	}

	public void setIsAdd(char isAdd) {
		this.isAdd = isAdd;
	}

	@Column(name = "IS_DELETE", nullable = false, length = 1)
	public char getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(char isDelete) {
		this.isDelete = isDelete;
	}

	@Column(name = "IS_UPDATE", nullable = false, length = 1)
	public char getIsUpdate() {
		return this.isUpdate;
	}

	public void setIsUpdate(char isUpdate) {
		this.isUpdate = isUpdate;
	}

	@Column(name = "IS_VIEW", nullable = false, length = 1)
	public char getIsView() {
		return this.isView;
	}

	public void setIsView(char isView) {
		this.isView = isView;
	}

}
