package co.id.pegadaian.pasg2.pojo;

// Generated Jan 21, 2013 10:52:40 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblRekeningIaMaster generated by hbm2java
 */
@Entity
@Table(name = "TBL_REKENING_IA_MASTER", schema = "PASG2")//tbl_rekening_ia_master
public class TblRekeningIaMaster extends AuditTrail implements java.io.Serializable {

	private String noRek;
	private String noCoa;
	private String description;
	private String saldoNormal;

	public TblRekeningIaMaster() {
	}

	public TblRekeningIaMaster(String noRek) {
		this.noRek = noRek;
	}

	public TblRekeningIaMaster(String noRek, String noCoa, String description, String saldoNormal) {
		this.noRek = noRek;
		this.noCoa = noCoa;
		this.description = description;
		this.saldoNormal = saldoNormal;
	}

	@Id
	@Column(name = "no_rek", nullable = false, length = 7)
	public String getNoRek() {
		return this.noRek;
	}

	public void setNoRek(String noRek) {
		this.noRek = noRek;
	}

	@Column(name = "no_coa", length = 5)
	public String getNoCoa() {
		return this.noCoa;
	}

	public void setNoCoa(String noCoa) {
		this.noCoa = noCoa;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "saldo_normal", length = 1)
	public String getSaldoNormal() {
		return this.saldoNormal;
	}

	public void setSaldoNormal(String saldoNormal) {
		this.saldoNormal = saldoNormal;
	}

}
