package co.id.pegadaian.pasg2.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblUserGroup generated by hbm2java
 */
@Entity
@Table(name = "TBL_USER_GROUP", schema = "PASG2")
public class TblUserGroup extends AuditTrail implements java.io.Serializable {

	public TblUserGroup(BigDecimal groupId, String userId) {
		super();
		this.groupId = groupId;
		this.userId = userId;
	}

	private BigDecimal groupId;
	private String userId;

	public TblUserGroup() {
	}
	
	
	@Id
	@Column(name = "GROUP_ID", nullable = false, scale = 0)
	public BigDecimal getGroupId() {
		return this.groupId;
	}

	public void setGroupId(BigDecimal groupId) {
		this.groupId = groupId;
	}

	@Id
	@Column(name = "USER_ID", nullable = false, length = 10)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}




}
