package co.id.pegadaian.pasg2.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblLookup generated by hbm2java
 */
@Entity
@Table(name = "TBL_LOOKUP", schema = "PASG2")
public class TblLookup extends AuditTrail implements java.io.Serializable {

//	private TblLookupId id;
//	private String createBy;
//	private Date createDate;
//	private String updateBy;
//	private Date updateDate;
//	private BigDecimal versi;
	private String lookupLabel;
	private BigDecimal noUrut;
	private String lookupName;
	private String lookupValue;

	public TblLookup() {
	}
	
	@Id
	@Column(name = "LOOKUP_NAME", nullable = false, length = 100)
	public String getLookupName() {
		return this.lookupName;
	}

	public void setLookupName(String lookupName) {
		this.lookupName = lookupName;
	}
	@Id
	@Column(name = "LOOKUP_VALUE", nullable = false, length = 100)
	public String getLookupValue() {
		return this.lookupValue;
	}

	public void setLookupValue(String lookupValue) {
		this.lookupValue = lookupValue;
	}
	


	public TblLookup(String createBy, Date createDate, String updateBy,
		Date updateDate, BigDecimal versi, String lookupLabel,
		BigDecimal noUrut, String lookupName, String lookupValue) {
	//super();
	this.lookupLabel = lookupLabel;
	this.noUrut = noUrut;
	this.lookupName = lookupName;
	this.lookupValue = lookupValue;
}
	
	@Column(name = "LOOKUP_LABEL", nullable = false, length = 200)
	public String getLookupLabel() {
		return this.lookupLabel;
	}

	public void setLookupLabel(String lookupLabel) {
		this.lookupLabel = lookupLabel;
	}

	@Column(name = "NO_URUT", scale = 0)
	public BigDecimal getNoUrut() {
		return this.noUrut;
	}

	public void setNoUrut(BigDecimal noUrut) {
		this.noUrut = noUrut;
	}

}
