package co.id.pegadaian.pasg2.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMenu generated by hbm2java
 */
@Entity
@Table(name = "TBL_MENU", schema = "PASG2")
public class TblMenu extends AuditTrail implements java.io.Serializable {

	private BigDecimal menuId;

	private char haveChild;
	private String menuName;
	private BigDecimal noUrut;
	private String params;
	private BigDecimal parentId;
	private String screenClass;
	private String isUsingGroovy;
	private String menuPage;

	public TblMenu() {
	}

	public TblMenu(BigDecimal menuId, char haveChild, String menuName,
			BigDecimal noUrut) {
		this.menuId = menuId;
		this.haveChild = haveChild;
		this.menuName = menuName;
		this.noUrut = noUrut;
	}

	

	public TblMenu(BigDecimal menuId, char haveChild, String menuName,
			BigDecimal noUrut, String params, BigDecimal parentId,
			String screenClass, String isUsingGroovy, String menuPage) {
		super();
		this.menuId = menuId;
		this.haveChild = haveChild;
		this.menuName = menuName;
		this.noUrut = noUrut;
		this.params = params;
		this.parentId = parentId;
		this.screenClass = screenClass;
		this.isUsingGroovy = isUsingGroovy;
		this.menuPage = menuPage;
	}

	@Id
	@Column(name = "MENU_ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getMenuId() {
		return this.menuId;
	}

	public void setMenuId(BigDecimal menuId) {
		this.menuId = menuId;
	}


	@Column(name = "HAVE_CHILD", nullable = false, length = 1)
	public char getHaveChild() {
		return this.haveChild;
	}

	public void setHaveChild(char haveChild) {
		this.haveChild = haveChild;
	}

	@Column(name = "MENU_NAME", nullable = false, length = 200)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "NO_URUT", nullable = false, scale = 0)
	public BigDecimal getNoUrut() {
		return this.noUrut;
	}

	public void setNoUrut(BigDecimal noUrut) {
		this.noUrut = noUrut;
	}

	@Column(name = "PARAMS", length = 400)
	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	@Column(name = "PARENT_ID", scale = 0)
	public BigDecimal getParentId() {
		return this.parentId;
	}

	public void setParentId(BigDecimal parentId) {
		this.parentId = parentId;
	}

	@Column(name = "SCREEN_CLASS", length = 200)
	public String getScreenClass() {
		return this.screenClass;
	}

	public void setScreenClass(String screenClass) {
		this.screenClass = screenClass;
	}

	@Column(name = "IS_USING_GROOVY", length = 1)
	public String getIsUsingGroovy() {
		return this.isUsingGroovy;
	}

	public void setIsUsingGroovy(String isUsingGroovy) {
		this.isUsingGroovy = isUsingGroovy;
	}

	@Column(name = "MENU_PAGE", length = 200)
	public String getMenuPage() {
		return this.menuPage;
	}

	public void setMenuPage(String menuPage) {
		this.menuPage = menuPage;
	}

}
